// DO NOT EDIT: FILE GENERATED BY 'tape-index'

"use strict";

Error.stackTraceLimit = Infinity;


var test = require("tape");

test("Modules coverage", function (t) {
	t.pass("Tests found for 'index.js'");
	t.fail("Tests missing for 'test.js'");
	t.end();
});

// Actual tests
require("./test/index.js");
